# Site settings, 기본정보 입력
title: 노력으로 발전하는 개발자 Blog
lang: ko-KR
since: 2023
beian:
rss: /feed.xml
baseurl: # the subpath of your site, e.g. /blog/
url: 'https://bakcheongkyung.github.io/' # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Dev Bakcheongkyung Portfolio.

# 主题颜色 red/green/blue (default:blue)
theme_color: blue

menu:
  - name: Home
    url: /
  - name: Categories
    url: /categories/
  - name: Tags
    url: /tags/
  - name: About
    url: /about/

# comments
disqus_shortname: bak-cheongkyung

# 프로필 영역
anthor:
  name: Bakcheongkyung
  email: draw.ch.b@gmail.com
  github_username: Bakcheongkyung

# footer 영역
social:
  - name: Github
    url: https://github.com/BAKCHEONGKYUNG
    icon: github
  - name: Email
    url: mailto:draw.ch.b@gmail.com
    icon: envelope
  - name: RSS
    url: /feed.xml
    icon: rss

# Build settings
destination: _site
encoding: utf-8
timezone: Asia/Seoul
asset_url: /assets

# Outoutting
permalink: /:year/:title/
paginate: 10 #Defaults : 5
paginate_path: /page/:num/
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: '<!--more-->'
incremental: false

# more config please click:http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_number_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

# Plugins
whitelist: []
gems:
  - jekyll-paginate-v2
  - jekyll-mentions # activesupport requires Ruby version >= 2.2.2
  - jemoji
  - jekyll-redirect-from
